targets:
  $default:
    builders:
      codo_gen_swagger:
        enabled: true

builders:
  generators:
    target: ":codo_gen_swagger"
    import: "package:codo_gen_swagger/builder.dart"
    builder_factories: ["generateSwagApi"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
